package yajco.fle.panels;

import java.awt.GridBagConstraints;
import javax.swing.JLabel;
import yajco.fle.panels.interfaces.Labeled;

/**
 *
 * @author Milan
 * @param <T> type
 */
public abstract class ConcreteConceptPanelBase<T> extends AbstractAccessiblePanel<T> implements Labeled {

    /**
     * Creates new form ConceptPanelBase
     */
    public ConcreteConceptPanelBase() {
        initComponents();
    }

    protected void addRowForProperty(String label, AbstractAccessiblePanel panel) {
        GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        JLabel jLabel = new JLabel(label);
        jLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jLabel, gridBagConstraints);
        
        panel.setToolTipText(label);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(panel, gridBagConstraints);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
