package yajco.fle.panels;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Label;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Milan
 * @param <T> type
 */
public abstract class ConcreteConceptPanelBase<T> extends AbstractAccessiblePanel<T> {

    /**
     * Creates new form ConceptPanelBase
     */
    public ConcreteConceptPanelBase() {
        initComponents();
    }

    protected void addRowForProperty(String label, AbstractAccessiblePanel panel) {
        GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.0;
        //gridBagConstraints.gridy = 0;
        add(new Label(label), gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        panel.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        add(panel, gridBagConstraints);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.0;
        //gridBagConstraints.gridy = 0;
        add(new Label("Pokus"), gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        panel.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        JPanel p = new JPanel();
        p.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        add(p, gridBagConstraints);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
